### PR TITLE
Misc Changes

### PR DESCRIPTION
**Pull request by Lupus590**

### CODE REVIEW

**Comment by Lupus590** [comment]
Doesn't include the new prompt, see discord for why.

This should be ready for merge if you're ok with it though.

**Comment by EmmaKnijn** [comment]
Let me take a quick look at the speaker api

**Comment by EmmaKnijn** [comment]
It's supposed to be `speaker.playNote("chime", 3, 12)`, see above commit

**Comment by Lupus590** [comment]
If you want to merge this you can, I'm going to make another PR for any other changes.

**Comment by EmmaKnijn** [comment]
Okay I will

**Pull request merged**
